only run action if changes detected

diff --git a/.github/workflows/check-rss-and-build.yml b/.github/workflows/check-rss-and-build.yml
--- a/.github/workflows/check-rss-and-build.yml
+++ b/.github/workflows/check-rss-and-build.yml
@@ -16,29 +16,29 @@ jobs:
         with:
           ref: ${{ github.head_ref }}
 
-      # - name: Fetch RSS Feed
-      #   uses: Promptly-Technologies-LLC/rss-fetch-action@v2
-      #   with:
-      #     feed_url: "https://www.radcrew.net/category/finalfantasy/feed"
-      #     file_path: "./latest-feed.json"
+      - name: Fetch RSS Feed
+        uses: Promptly-Technologies-LLC/rss-fetch-action@v2
+        with:
+          feed_url: "https://www.radcrew.net/category/finalfantasy/feed"
+          file_path: "./latest-feed.json"
 
-      # - name: Check if RSS feed has changed
-      #   id: check_changes
-      #   run: |
-      #     if git diff --exit-code ./latest-feed.json; then
-      #       echo "No changes detected in RSS feed"
-      #       echo "changes_detected=false" >> $GITHUB_OUTPUT
-      #     else
-      #       echo "Changes detected in RSS feed"
-      #       echo "changes_detected=true" >> $GITHUB_OUTPUT
-      #     fi
+      - name: Check if RSS feed has changed
+        id: check_changes
+        run: |
+          if git diff --exit-code ./latest-feed.json; then
+            echo "No changes detected in RSS feed"
+            # Exit code 78 is a neutral exit code in GitHub Actions
+            # It indicates that the job is skipped, not failed or succeeded
+            exit 78
+          else
+            echo "Changes detected in RSS feed"
+          fi
 
-      # - name: Commit and push changes to repository
-      #   if: steps.check_changes.outputs.changes_detected == 'true'
-      #   uses: stefanzweifel/git-auto-commit-action@v5
-      #   with:
-      #     commit_message: "Update RSS feed"
-      #     file_pattern: "*.json"
+      - name: Commit and push changes to repository
+        uses: stefanzweifel/git-auto-commit-action@v5
+        with:
+          commit_message: "Update RSS feed"
+          file_pattern: "*.json"
 
       - name: Setup Node.js
         uses: actions/setup-node@v3
@@ -55,7 +55,6 @@ jobs:
         run: npm run build
 
       - name: Deploy to Cloudflare Pages
-        # if: steps.check_changes.outputs.changes_detected == 'true'
         uses: cloudflare/wrangler-action@v3
         with:
           apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
